[package]
version = "0.1.0"
name = "host"
edition = "2021"

[dependencies]
zkm-sdk.workspace = true
zkm-verifier.workspace = true
clap = { version = "4.0", features = ["derive"] }
hex = "0.4.3"
serde = "1.0"
serde_json = "1.0"
bincode = "1.3.3"

[build-dependencies]
zkm-build.workspace = true
